[package]
name = "julia_set_explorer"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Lachlan Doig <lachjd@protonmail.com>"]
description = "Interactive visualisation of Julia sets"

[dependencies]
minifb = "0.24.0"
rayon = "1.5.1"
image = "0.24.5"
mandelbruhst-cli = "0.1.0"